Made some major improvements at chaos worker
zeebe-io/zeebe-cluster-testbench pull request #114
Opened 2020-11-10 16:11 UTC by Zelldon

I did more a integration test with the simple monitor and a camunda cloud cluster, which I created manually. In the end I was able to run a chaos experiment based on the given payload and complete the job successfully. There were a lot of failed and retried jobs in between :sweat_smile: 

![run](https://user-images.githubusercontent.com/2758593/98699336-52132980-2377-11eb-9232-461e13e5215a.png)

Cleaned up the worker script. I have a local script to run tests against simple monitor.
Fixes some problems in the job handler code.
 The runChaosExperiments has returned an positive value, which causes the job worker to fail the job and retry, which we don't want. The generation of the test result hasn't worked 100% correct. If the message contained white spaces it was also splitted in separate entries. Previous we haven't read the input correctly, since we used the wrong function.

2020-11-10 17:08 UTC, pihme requested changes
Looks very good. 

There are two suggestions for improvement. 

And a couple of lines were so cryptic that I am hoping we can make them clearer.

2020-11-10 17:08 UTC, pihme commented on core/chaos-workers/handlerUtil.sh
> +     '{testResult: $result, failureMessages: $failures | split(","), failureCount: 1, metaData: {}}'
Can we add some brackets here? 

In particular I don't understand `$failures | split(",")` 
Is failures piped into split? Isn't split the inverse operation to joined in line 73?

I find this line and line 73 very confusing. So if there is something you can add in terms of syntactic sugar or comments, I would appreciate it.

2020-11-10 17:08 UTC, pihme commented on core/chaos-workers/handlerUtil.sh
> +      return 0 # if we return an error code the job worker would fail the job
Thanks for this comment!

2020-11-10 17:53 UTC, Zelldon commented on core/chaos-workers/handleJobTest.sh
> +ZEEBE_ADDRESS='33c00aed-cf34-4c8a-867d-161ee9c8943d.zeebe.ultrawombat.com:443'
Hm I think we can use also different ones, but this makes it easier to understand if you have similar value I assumed. Why does it matter?

2020-11-10 17:58 UTC, Zelldon commented on core/chaos-workers/handleJob.sh
> +  || (createFailureMessage "Namespace '$NAMESPACE' doesn't exist" && exit 0)
Yeah I need to dig deep into this a bit. I seems that the script somehow still continues. It is on my todo list, but I aggree was also my first opinion but later I was not so sure anymore :D 
Follow up https://github.com/zeebe-io/zeebe-cluster-testbench/issues/115

2020-11-10 17:59 UTC, pihme commented on core/chaos-workers/handleJobTest.sh
> +ZEEBE_ADDRESS='33c00aed-cf34-4c8a-867d-161ee9c8943d.zeebe.ultrawombat.com:443'
Well, maybe I am just affected by me spending the better part of a day to clean up the accidental commit of an actual secret yesterday.
Looking at it like this, it makes me wonder whether the secrets are real and it makes me nervous. 

If I had something like "12345678abd-123-abc.." etc. it would mimic the look of it but it would also be obvious that these are just bogus values.

2020-11-10 18:08 UTC, Zelldon commented on core/chaos-workers/handlerUtil.sh
> +     '{testResult: $result, failureMessages: $failures | split(","), failureCount: 1, metaData: {}}'
Yeah I agree it is a bit confusing. It was a hard fight :sweat_smile: 

The problem I wanted to solve was the following. I can get inputs like: `function "Namespace not found"` **or** `function "Namespace not Found" "Other Error"`, before what happens was that it created an [array which looked like this](https://jqplay.org/s/wLyxJ6zH2N): `["Namespace","not","Found","Other","Error"]`. The issue was that it just takes the array and replaced all white spaces. 
[What we want is ](https://jqplay.org/s/7zMNEeubWb): ["Namespace not Found","Other Error"]. So I need as an input a string which looks like this: `"Namespace not Found, Other Error"`. The `split` method is an function defined by `jq`, see [here](https://stedolan.github.io/jq/manual/)

So what I do is to join the array entries via comma to split time later on correctly via `split`. Split makes sure that at the end a `json array` is return, which means it will add the `\"` and `[` `]` brackets.

2020-11-10 18:36 UTC, Zelldon commented on core/chaos-workers/handleJobTest.sh
> +ZEEBE_ADDRESS='33c00aed-cf34-4c8a-867d-161ee9c8943d.zeebe.ultrawombat.com:443'
ok i can change that

2020-11-10 18:57 UTC, pihme commented on core/chaos-workers/handlerUtil.sh
> +     '{testResult: $result, failureMessages: $failures | split(","), failureCount: 1, metaData: {}}'
Maybe some comments in the script with examples of what the value looks like in the different stages would be helpful.

2020-11-10 20:14 UTC, Zelldon commented
Thanks @pihme for your review. I applied your hints :)

2020-11-11 09:01 UTC, pihme approved these changes
Thanks for the changes. Looks very good.

2020-11-11 09:10 UTC, Zelldon commented
bors r+

2020-11-11 09:13 UTC, merged