chore(scripts): add script to help a little bit with working with chaos test logs
zeebe-io/zeebe-cluster-testbench pull request #141
Opened 2020-11-16 16:49 UTC by pihme

Not proud of it. But took me enough time to find these lines, so I better want to share it.

2020-11-17 09:46 UTC, Zelldon approved these changes
Cool stuff @pihme :rocket:

2020-11-17 09:46 UTC, Zelldon commented on scripts/chaos-log-chunker.sh
> +fi
```suggestion
chaosWorkerPod="$(kubectl get pods -o json -l app=chaos-worker | jq -r '.items[].metadata.name')"
```

2020-11-17 09:46 UTC, Zelldon commented on scripts/chaos-log-chunker.sh
> +kubectl cp "$1":/home/chaos/zeebe-chaos/chaos-experiments/camunda-cloud/chaostoolkit.log .
```suggestion
kubectl cp "$chaosWorkerPod":/home/chaos/zeebe-chaos/chaos-experiments/camunda-cloud/chaostoolkit.log .
```

2020-11-18 09:31 UTC, pihme commented on scripts/chaos-log-chunker.sh
> +grep -l "failing this experiment" *.log-chunk | awk '{printf "mv %s %s-failed\n", $1, $1}' FS=/ | sh
@Zelldon I am in a bit of a pickle here. 

This version of the script that does work, but shellcheck doesn't like it. https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe-cluster-testbench/detail/script-for-chaos-worker-log/4/pipeline

If I apply the shellcheck suggestion then it doesn't work:
```
 user@BlackBox:/mnt/c/dev/github/zeebe-cluster-testbench/scripts$ ./chaos-log-chunker.sh
tar: removing leading '/' from member names
mv: cannot move '.' to '.-failed': Device or resource busy
mv: cannot move '.' to '.-failed': Device or resource busy
mv: cannot move '.' to '.-failed': Device or resource busy
mv: cannot move '.' to '.-failed': Device or resource busy
```
I guess it is because now awk command is wrong. 

Any ideas how to remedy this?

(I do want to keep shellcheck)

2020-11-24 16:16 UTC, Zelldon commented on scripts/chaos-log-chunker.sh
> +grep -l "failing this experiment" *.log-chunk | awk '{printf "mv %s %s-failed\n", $1, $1}' FS=/ | sh
Sorry I missed that I will take a look tomorrow

2020-11-25 14:59 UTC, Zelldon commented on scripts/chaos-log-chunker.sh
> +grep -l "failing this experiment" *.log-chunk | awk '{printf "mv %s %s-failed\n", $1, $1}' FS=/ | sh
So I tried with adding `--` before `*.log-chunk` this works, but it will btw not work if there is no error in the log then it just dies silently and will not clean up the chunks.

Maybe it would be easier to just do something like this:


```
failedChunks=$(grep -l "failing this experiment" -- *.log-chunk)

for chunk in $failedChunks
do
  mv "$chunk" "$chunk-failed"
done
```

2020-11-25 15:05 UTC, Zelldon requested changes

2020-11-25 15:05 UTC, Zelldon commented on scripts/chaos-log-chunker.sh
> +grep -l "failing this experiment" *.log-chunk | awk '{printf "mv %s %s-failed\n", $1, $1}' FS=/ | sh
```suggestion
failedChunks=$(grep -l "failing this experiment" -- *.log-chunk)

for chunk in $failedChunks
do
  mv "$chunk" "$chunk-failed"
done
```

2020-11-26 14:13 UTC, pihme commented on scripts/chaos-log-chunker.sh
> +grep -l "failing this experiment" *.log-chunk | awk '{printf "mv %s %s-failed\n", $1, $1}' FS=/ | sh
Thanks

2020-11-26 14:29 UTC, pihme commented
All implemented as per your suggestion. Plus rebased and log compacted. Enjoy!

2020-11-26 14:35 UTC, Zelldon approved these changes
awesome :) :+1:

2020-11-26 14:36 UTC, pihme commented
bors r+

2020-11-26 14:47 UTC, merged