fx(core): replace null values with n/a to prevent misalignment
zeebe-io/zeebe-cluster-testbench pull request #204
Opened 2021-01-07 17:41 UTC by pihme

closes #203 

Changes:
- null values in the test report will now be replaced with "n/a" to preserve column layout

2021-01-07 17:42 UTC, pihme commented
@npepinpe Didn't you say you want a little more exposure to the testbench code? What about a little review as a first baby step?

2021-01-07 18:40 UTC, npepinpe requested changes
Looks good generally, I'm very curious to know why this is the behaviour but I couldn't find anything in the docs (other than their suggestion to add empty strings instead of null if you want to preserve them)

2021-01-07 18:40 UTC, npepinpe commented on core/src/main/java/io/zeebe/clustertestbench/handler/RecordTestResultHandler.java
> +  protected static List<Object> buildRowDataForSheet(final Input input) {
I would propose instead to add all the fields, and before sending it, iterate through them and replace null with NA. I think we're less likely to have someone forget to replace null with NA if we do this in the future. We could also extract that to a method, i.e.

```java
protected static List<Object> buildRowDataForSheet(final Input input) {
  final List<Object> result = new ArrayList<>();
  result.add(input.getRegion());
  // ... add more fields

  // null values are omitted from the result sheet, so insert a placeholder in order to preserve the layout
  final List<Object> sanitizedResult = result.stream().map(o -> o == null ? NA : o).collect(Collectors.toList());
  // ...
}
```

2021-01-07 18:40 UTC, npepinpe commented on core/src/test/java/io/zeebe/clustertestbench/handler/RecordTestResultHandlerTest.java
> +  void testShouldWriteValueIntocorrectColumn(
```suggestion
  void testShouldWriteValueIntoCorrectColumn(
```

2021-01-07 18:40 UTC, npepinpe commented on core/src/test/java/io/zeebe/clustertestbench/handler/RecordTestResultHandlerTest.java
> +class RecordTestResultHandlerTest {
We could add a test that fails if someone adds a field to `Input` (which ends up in the results) but forgets to replace null with NA. All fields in `Input` are by default null, no? Then we create a default Input, pass it, then look if any columns still have null (and fail if so).

2021-01-08 08:20 UTC, npepinpe approved these changes
:tada:

2021-01-08 08:23 UTC, pihme commented
bors r+

2021-01-08 08:31 UTC, merged