Replace chaos toolkit usage
zeebe-io/zeebe-cluster-testbench pull request #269
Opened 2021-04-07 06:15 UTC by Zelldon

# Description

 The old simple chaos process was replaced by two processes.

![chaosToolkit](https://user-images.githubusercontent.com/2758593/113818490-1c346e80-9778-11eb-9c67-b7eb53c5aa09.png)
![chaosExperiment](https://user-images.githubusercontent.com/2758593/113818495-1ccd0500-9778-11eb-9f14-08c13cdc4fb5.png)

Furthermore the old zbctl chaos script worker was replaced by a new application, which contains multiple workers.

The workers are written in kotlin. Some of them execute scripts in the `zeebe-chaos` repository. The new workers and process models give us more visibility and maintainability. The new workers (which run the script logic) can be replaced step by step by workers written in other languages. One of the new workers reads all experiments for a given cluster plan to determine
what kind of experiments and which steps need to be executed. This new application and the corresponding process models allows to replace chaos toolkit completely.

You can also read more about it here https://zeebe-io.github.io/zeebe-chaos/chaos_experiment/bpmn/2021/04/03/bpmn-meets-chaos-engineering.html

I executed the models on a test production m cluster with success.

The root `chaosToolkit` process: 

![run-successful](https://user-images.githubusercontent.com/2758593/113818814-aaa8f000-9778-11eb-997c-6d7d0346a3fd.png)

Some of the experiment processes:

![exp2-success](https://user-images.githubusercontent.com/2758593/113818995-f3f93f80-9778-11eb-83e1-e3f67c0ff1d9.png)
![exp1-success](https://user-images.githubusercontent.com/2758593/113818996-f491d600-9778-11eb-8b0f-347ce0fd693f.png)

If you want to see how it looks like if we have an timeout:

![timeout-corrupt](https://user-images.githubusercontent.com/2758593/113819023-ffe50180-9778-11eb-96fa-033d3f4e8ea9.png)

*Note:* I called the process `chaosToolkit` out of sentimentality.

If you fine with the changes I would adjust the docs as a follow up.

2021-04-07 06:20 UTC, Zelldon commented
Might make sense to move the code into the other application? Happy to hear your thoughts @pihme

2021-04-07 11:09 UTC, pihme requested changes
First let me say that I really like this project. I am looking forward to expanding it!

However, there are some issues with the current PR:
* We need an aggregated test result PASS/FAIL for Jenkins QA run
* This should currently not be merged into develop

Nico is currently working on a way to have multiple versions of testbench corresponding to multiple major versions of Zeebe. See #251 

In the current state `stable/0.26` is for development based on 0.26. It has a working deploy pipeline. However, `develop` is earmarked for development based on 1.0, and it currently has no working deploy pipeline. 

Also, we currently don't merge to develop because the deploy pipeline might still deploy to 0.26, which is a bit of a mess.

So assuming that your changes are meant for 0.26, please merge it into `stable/0.26` instead. Feel free to use the backport action to "backport" it `devleop`. We can then merge it later once the deploy pipeline for 1.0 is up and running.

Besides these two issues, which need changes, there is also the question of what is our long term vision. I am fine with the changes as an iterative step. I don't think they represent a long-term solution though.

Long term I see a spectrum of options. The spectrum is marked on one hand by having a single deployment for everything, and on the other hand by having several deployments and more of a micro service style.

Personally, I feel the second option is much more interesting. 

So in that scenario, I would see the chaos workers as their own deployment and potentially their own repo. Not sure what you meant by "the other application", but maybe you had something like this in mind. This deployment would contribute/deploy the `chaosToolkit` process and all the workers defined therein. 

The workers may implement `TestDriver`. But this is more along the lines of "use it if it makes sense".
 
If we think more of a single deployment, then I would try to sort it more into the existing module structure. But not sure this is the direction we want to go.

2021-04-07 11:15 UTC, Zelldon commented on pom.xml
> +            <mutator>AOD</mutator>
Looks like whitespace removal

2021-04-07 11:16 UTC, Zelldon commented on workflows/chaos-test.bpmn
> -<?xml version="1.0" encoding="UTF-8"?>
Why :sweat_smile: we have git for that :laughing:

2021-04-07 11:17 UTC, pihme commented on workflows/chaos-test.bpmn
> -<?xml version="1.0" encoding="UTF-8"?>
It's for Operate. All the old processes have a "Legacy" prefix.

2021-04-07 11:18 UTC, Zelldon commented on workflows/chaos-test.bpmn
> -<?xml version="1.0" encoding="UTF-8"?>
Not sure whether I get it sorry :sweat_smile: Maybe you can explain it f2f

2021-04-07 11:20 UTC, pihme commented on workflows/chaos-test.bpmn
> -<?xml version="1.0" encoding="UTF-8"?>
It's just a minor thing:
![image](https://user-images.githubusercontent.com/14032870/113858365-ed33f200-97a3-11eb-99ed-25e05902845e.png)

2021-04-07 11:55 UTC, Zelldon commented on workflows/chaos-test.bpmn
> -<?xml version="1.0" encoding="UTF-8"?>
Ok sure can do

2021-04-07 12:02 UTC, Zelldon commented on workflows/chaosToolkit.bpmn
> +<?xml version="1.0" encoding="UTF-8"?>
Gotcha. I think I will do it via output mappings on the process, since if the experiments run through everything is fine. We can build the output/testresult based on the existing payload.

We don't expect errors of these experiments, all steps are internally retried. So the only failure case can then happen is timeout (this was also before the case). I will put then different mapping on the end of the event sub process.

2021-04-08 12:17 UTC, Zelldon commented
I reworked the chaos process and introduce a new model to run the actions, which can then also have timeouts for each step. So we have a timeout for each step and a global timeout. Furthermore the testResults are build together via output mappings.


![errorresult](https://user-images.githubusercontent.com/2758593/114025026-f80a8780-9874-11eb-8d16-385e31a32dc8.png)
![errorresultexp](https://user-images.githubusercontent.com/2758593/114025022-f771f100-9874-11eb-8ad5-4c429e8e95ba.png)
![errorresultaction](https://user-images.githubusercontent.com/2758593/114025025-f80a8780-9874-11eb-9ae1-bb81c9999b66.png)

The failure message shows now only for which cluster plan the experiments it fails. I think this is enough for now, the medic needs to anyway check operate where he can find the related information. To get the failed experiment out of the variables is a bit harder, since on boundary events we cant access the scope of the underlying activity.

2021-04-08 12:23 UTC, Zelldon commented on workflows/chaos-test.bpmn
> -<?xml version="1.0" encoding="UTF-8"?>
I deployed it manually with the different name

2021-04-08 12:24 UTC, Zelldon commented
Hey @pihme thanks for your review I applied as discussed your requested changes. Please have another look and let me know what you think

2021-04-08 12:26 UTC, pihme commented
@Zelldon still merging to develop, not sure if you can change this while the PR is open. Just wanted to mention it before I look at it again. Maybe I need to do the review on a new PR.

2021-04-08 12:26 UTC, Zelldon commented
@pihme you're right. I changed the base now :)

2021-04-08 12:36 UTC, pihme requested changes
Quick response before I go into meetings for the next 90mins:

* I still don't understand how a failed test is reported to the outside. Maybe you want to override the test result in `chaosToolkit-> Failure to run chaos experiments`. Or maybe you want to initialize it to failed and only overwrite it in the case of a successful run. Maybe I missed something, but I couldn't find it straight away
* The timeout of 3h in `chaosExperiment` seems very high. I guess it's a worst case scenario and the other timeouts should fire before. So I guess it can stay like this. But I would prefer a bit of a tighter timeout.

2021-04-08 12:44 UTC, Zelldon commented
Chaos experiments can't fail they just time out, which is then handled on root level as failed experiment. This means output mapping will create a testReport payload which contains failures message etc. Side note: internally scripts are retried endless.

2021-04-08 12:49 UTC, pihme approved these changes
Love it! :tada:

2021-04-08 12:52 UTC, Zelldon commented
bors r+

2021-04-08 12:55 UTC, merged