refactor(chaos): migrate "await-processes-with-result.sh" to Kotlin
zeebe-io/zeebe-cluster-testbench pull request #332
Opened 2021-05-12 14:53 UTC by pihme

- Also extract reusable methods in abstract class
- Also activate Idea Kotlin code conventions
- removed redundant semicolons

2021-05-12 14:55 UTC, pihme commented
@Zelldon What is the way you usually test this?

2021-05-12 18:11 UTC, Zelldon requested changes
Hey @pihme thanks so much for doing this and joining me in migrating these scripts ! :rocket: 

Yeah this test topic is interesting and you hit a sensitive spot. I normally did it manually, this means I have two camunda cloud clusters, one acts as testbench and one as target cluster and then I run the worker with the corresponding credentials and create specific process instances for it. I can give you the scripts or push them which helps on setting these things up, but I'm not sure whether this is really the solution, since it is not optimal and takes a bit time and knowledge to setup.

Ideally we would have some more automated tests, but this was not that simple and I had not really time to invest in this. I thought about having a testcontainer and running the migrated actions against that, but currently we can't really verify whether this worked. There is currently no easy way to get results out of the Zeebe test container etc. You could add ZeeQS but this makes the setup more complex and adds another dependency. 

In the time of writing this I had another Idea, which brings me also to the next point. i would prefer to use a composition instead of inheritance, there are several resources out there for that. But to strengthen my point we could have then dependency injection, which gives us the possibility to write tests more easily. We could replace the returned client in a test environment, so we could for example use the EmbeddedBrokerRule with a normal client. This would also allow us to verify whether everything worked as expected via the RecordingExporter. Should I create a follow up issue for that?

Please approach me if the explanation was not really clear :) 

Greets
Chris

2021-05-14 13:43 UTC, pihme commented on core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
> +                    .join()
I knew I had forgotten something ;-)

2021-05-14 14:06 UTC, pihme commented on core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
> +            deployModel(it, PROCESS, "one_task.bpmn")
Now that I think about it, I don't think the do-while loop is a good idea. It could literally run forever. That is because the worker doesn't know about the timeouts in Zeebe.

2021-05-14 14:09 UTC, Zelldon commented on core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
> +            deployModel(it, PROCESS, "one_task.bpmn")
Thats why we have the boundary events in the model and the timeout defined in the experiment json

2021-05-14 14:12 UTC, pihme commented on core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
> +            deployModel(it, PROCESS, "one_task.bpmn")
Still don't understand how any of these will terminate the do-while loop.

2021-05-14 14:13 UTC, Zelldon commented on core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
> +            deployModel(it, PROCESS, "one_task.bpmn")
Gotcha you're right😅

2021-05-14 17:59 UTC, pihme commented
@Zelldon Thanks for nudging me away from inheritance. It is so easy to follow familiar paths. I now embraced your idea of composition. And I also made stronger attempts to write idiomatic Kotlin.

So the method `deployModel` is now an extension method for `ZeebeClient`.
And the logic to construct the zeebe client is not captured in an object that is then composited. Instead, it is captured in a function signature. The function has a default implementation, but it can also be explicitly overridden - e.g. in a test.

Then I had a look at testing. There is good and bad stuff. The good stuff is call chaining when defining mocks. This is such a game changer in my mind!

The bad stuff is that it doesn't work as flawlessly as one could imagine. There are some weird quirks and at least so far I don't know in advance whether I use the tools in a way that is safe and works, or whether they will surprise me.

Anyways, very exciting to learn more about Kotlin. I really start to like it.

Current code is to be seen more as a basis for discussion and less as a final proposal.
And I am also looking forward to talking more about testing. @korthout polished the Dev stage, so it is time to take it for a spin.

Ah, so much fun with so many new toys :smiley:

2021-05-17 06:27 UTC, Zelldon approved these changes
Hey @pihme I'm happy that you have so much fun with kotlin as I have :grinning: 

In general I like your changes ! As you know I'm not a big fan of mocking things. I always have the feeling and fear that we couple the test to much on the implementation details, which can cause a lot of failing tests if you change just the order of some loc. [There is an interesting Test Desiderata from Kent Beck, which covers this.](https://www.youtube.com/watch?v=bvRRbWbQwDU&list=PLlmVY7qtgT_lkbrk9iZNizp978mVzpBKl&index=2&ab_channel=KentBeckKentBeck)

I prefer more behavior tests where we verify that the end result is correct no matter how we achieved it. Like I wrote before, having a broker or engine and deploying a model, creating an instance having the worker running and see that it does the work as expected, via the log.

If you want to keep it like this, I'm also fine just wanted to express my feelings on that :)

2021-05-17 06:27 UTC, Zelldon commented on core/chaos-workers/chaos-worker/src/test/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandlerTest.kt
> +        }
You know you can hunt me with things like this :D

2021-05-17 06:27 UTC, Zelldon commented on core/chaos-workers/chaos-worker/src/test/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandlerTest.kt
> +        )
Even if I'm not a fan of mocks I like how its done looks quite elegant.

2021-05-17 09:16 UTC, pihme commented on core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
> +    Awaitility.setDefaultPollInterval(Duration.ofHours(1))
Yes, it's a bit coarse, but we can still refine it later

2021-05-17 09:17 UTC, pihme commented on core/chaos-workers/chaos-worker/src/test/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandlerTest.kt
> +        }
Just as you can hunt me with spinning up an engine in a simple unit test and then dealing with the complexities of asynchronous processes :D

2021-05-17 14:12 UTC, pihme commented
Successfully tested on Dev stage

2021-05-17 14:12 UTC, pihme commented
bors r+

2021-05-17 14:15 UTC, merged