fix(chaos): print system error together with system out
zeebe-io/zeebe-cluster-testbench pull request #369
Opened 2021-05-20 14:53 UTC by Zelldon

Previously the output streams have been printed after another, which can
cause confusion and makes it not really visible what is happening.

Furthermore the worker thread was blocked, until the process was done.
This cause problems on handling jobs, not terminating the process after
some time and we are not seeing what is going on.

For more information read https://github.com/zeebe-io/zeebe-cluster-testbench/issues/368

closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/368

Sorry with bothering you all the time @pihme

2021-05-20 16:59 UTC, pihme requested changes
Hmm, not sure I understood everything. Here is my take on it:

- I don't think logging asynchronously alone is doing what you want it to do. 
- I think you also need to include the `process.waitFor(timeoutInSeconds, TimeUnit.SECONDS)` because this one is also blocking the thread
```
  public boolean waitFor(long timeout, TimeUnit unit) throws InterruptedException {
    long startTime = System.nanoTime();
    long rem = unit.toNanos(timeout);

    while(true) {
      try {
        this.exitValue();
        return true;
      } catch (IllegalThreadStateException var9) {
        if (rem > 0L) {
          Thread.sleep(Math.min(TimeUnit.NANOSECONDS.toMillis(rem) + 1L, 100L));
        }

        rem = unit.toNanos(timeout) - (System.nanoTime() - startTime);
        if (rem <= 0L) {
          return false;
        }
      }
    }
  }
```

- And I guess once you do that you will get the same `IllegalThreadStateException` that the `waitFor` is using - if you call `process.exitValue()` too soon -  so the rest of the method needs to go into the async block as well.
- And now that I think about it, we might want to fail the job or throw an error in the else case, so that Zeebe knows what happened, and doesn't need to wait for the timeout

And then, we have a nice example for an asynchronous worker.

2021-05-20 17:01 UTC, pihme commented
Oh and since we are in Kotlin, we might also look at https://kotlinlang.org/docs/coroutines-guide.html

2021-05-20 17:09 UTC, Zelldon commented
Yeah I dont wanted to open that box, but I hope soon 😁


The waitFor is ok. I want to block there, there I have a timeout. But on the consuming the output stream I had no timeout which means the process will run forever and we forever consume its output. Forever because the scripts retry on errors. 

I want to consume the output async and want to wait for either exit or timeout. What ever comes first will be then handled. On timeout I destroy the process.

2021-05-21 07:17 UTC, pihme approved these changes
lgtm :tada:

2021-05-21 07:18 UTC, pihme commented
bors r+

2021-05-21 07:21 UTC, merged