Log received cluster info
zeebe-io/zeebe-cluster-testbench pull request #391
Opened 2021-06-10 15:46 UTC by korthout

It is not always clear what is returned by the cloudAPI. Let's print out
the results at debug level to make it easier to debug when things have
changed.

Specifically, this might help to find out why the operate url is null.

relates to #380

2021-06-11 05:56 UTC, pihme requested changes
I like the idea of logging the requests to be able to diagnose what is going on.

The proposed change is ok, but probably too late in the request processing sequence. This way we will only print out those bits which were successfully deserialized and mapped.

I would propose to use a request filter instead. We already have one for bad requests `BadRequestResponseFilter`. 

The only tricky thing is to mark and reset the input stream, as described here: https://stackoverflow.com/questions/36676017/jax-rs-2-print-json-request

For an all bells and whistles implementation look here: https://github.com/kleben/jersey/blob/master/core-common/src/main/java/org/glassfish/jersey/filter/LoggingFilter.java

But we probably need less than that.

2021-06-15 13:05 UTC, korthout commented
The request filter works, (I've tested it on `1.x-dev`), but it's a bit hard to read, since it does not also print the requested url. It also seems to cut-off after about 1k chars and it logs all responses, including all retries for `QueryClusterStatus` and such, leading to relatively many logs produced. Lastly, lgtm found some problems with this code.

The goal of these logs was gain insights into the responded data, but we can also just inspect https://github.com/camunda-cloud/console/blob/master/backend/routes/api/CustomerClusterRouter.ts#L285-L315 for changes. Perhaps we can even come to an understanding with the console team, that they let us know about breaking changes. WDYT?

2021-06-15 13:18 UTC, pihme commented
>  but it's a bit hard to read, since it does not also print the requested url. 

I think you can get the the URI from request context

> It also seems to cut-off after about 1k chars 

That's strange.

> and it logs all responses, including all retries for `QueryClusterStatus` and such, leading to relatively many logs produced. 

The many logs doesn't bother me too much. I think we should be able to filter these log lines out because it is a distinct logger. 

> The goal of these logs was gain insights into the responded data, but we can also just inspect https://github.com/camunda-cloud/console/blob/master/backend/routes/api/CustomerClusterRouter.ts#L285-L315 for changes. Perhaps we can even come to an understanding with the console team, that they let us know about breaking changes. WDYT?

I don't think them letting us know about breaking changes is a viable option. I would be hard pressed to define which change is a breaking one. So for them to keep track of what we use and how important it is for us - I think that is too much to ask.

What we might discuss, though, is whether we can provide acceptance tests. These could be JS tests, maintained by either party. And they could run them alongside their other tests - and then alert us when any of the tests breaks. 

Still, I am unsure whether we want to invest that effort given that the breaking changes so far were once a quarter and usually not too bad.

I would definitely prefer to keep the logging class inside the code base. if you are worried about the log volume we could have it inactive, but we would be able to reactivate it when we need to diagnose something

2021-06-16 05:23 UTC, pihme requested changes

2021-06-16 16:10 UTC, korthout commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/EntityLoggingFilter.java
> +    if (responseContext.hasEntity()) {
I'd rather not, this was created to log responded entities.

2021-06-16 17:15 UTC, korthout commented
@pihme Please have a look at my most recent (5) commits and let me know what you think

2021-06-17 11:45 UTC, pihme requested changes
Not sure what happened here. Maybe it's just too hot these days :smile:

2021-06-17 11:45 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/EntityLoggingFilter.java
> +    final var entity = readEntityFromStream(stream);
```suggestion
    final var entity =  IOUtils.toString(stream, StandardCharsets.UTF_8);

```

from `org.apache.commons.io`

2021-06-17 11:45 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/EntityLoggingFilter.java
> +  private String readEntityFromStream(final InputStream stream) throws IOException {
I am not an expert on IO streams, but this seems to be wrong in so many ways.

`numRead = stream.read(entity, totalRead, MAX_ENTITY_SIZE)` skips the first `totalRead` bytes in the `entity` array and then starts writing from there, possibly exceeding the size of the array

Then `new String(entity, 0, Math.min(numRead, MAX_ENTITY_SIZE)` copies the array starting at index 0, where maybe nobody has written anything, because of the line above. Depending on `numRead` it might not reach to the point where something was written.

And the whole loop always reads `MAX_ENTITY_SIZE` or less, but since its a loop in total the code might read more than `MAX_ENTITY_SIZE`. 

Also the loop condition I think should be `> -1`. As far as I know, a result of 0 may be okay and simply means the stream has no data yet, but more data might come in in the future. (E.g. if the response is a DVD worth of data, there might be situations where the communication is still ongoig while the receiver starts processing the response).

Anyways, I feel this is getting a bit out of hand for the problem we are trying to solve. The whole business about the `MAX_ENTITY_SIZE` is only a safety measure in case the response is indeed a DVD. Because then the buffered stream would blow memory. 

Since we can expect reasonably short responses, I think it is good enough to copy everything that is there, and there is a utility function which does just that. (see other comment)

2021-06-17 15:51 UTC, korthout commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/EntityLoggingFilter.java
> +  private String readEntityFromStream(final InputStream stream) throws IOException {
I just worked from what we had available. I don't think agree with all your comments (although you might be right, I'm no IO Streams expert either and perhaps I misread the docs), but I absolutely agree that simpler is better. So let's just switch to commons.io for this one.

2021-06-17 17:17 UTC, korthout commented
@pihme did what you suggested, and played around a bit with the debug level logging configuration. Please have another loook

2021-06-21 08:17 UTC, pihme approved these changes
Good stuff :tada:

2021-06-23 11:29 UTC, korthout commented
bors merge

2021-06-23 11:32 UTC, merged