Improve testbench worker logging
zeebe-io/zeebe-cluster-testbench pull request #597
Opened 2022-03-09 17:48 UTC by korthout

This is a work in progress

closes #344

2022-03-11 13:57 UTC, korthout commented
@pihme I'm not sure anymore how to test this on dev. Any help would be appreciated 🙇

2022-03-14 08:46 UTC, pihme requested changes
Good start. Some suggestions for improvements.

2022-03-14 08:46 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/util/LogDetails.java
> +public final class LogDetails {
:x: I think this should create an auto-closable context which calls `MOC.clear()` in its `close()` method. This now writes into a log context on the thread, but doesn't remove those details. So any subsequent call on the same thread would use the same details. If the next job worker also calls `LogDetails.setMOCForJob(job)` it might work. But if the next job handler has less variables, it will not clear the variables it doesn't have.

If, however, this class would create a log context, then the job handler could become:
```
try (final logContext = LogDetails.forJob(job)) {
  ...
}
```

And once we have this general structure, we can also make this a decorator around a job handler. And add this decorator in `io.zeebe.clustertestbench.bootstrap.Launcher#registerWorker`

2022-03-14 08:46 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/util/LogDetails.java
> +public final class LogDetails {
:x: Please also add a test for this class (e.g. after `setMOCForJob(job)` is called, then `MOC` has certain contents.

`ActivatedJobStub` might be helpful here

2022-03-14 08:46 UTC, pihme commented on core/src/main/resources/log4j2.xml
> +    <Logger name="io.zeebe.clustertestbench.cloud.filter" level="debug" additivity="false"/>
:x: I think this produces too much noise. Some requests are small, but some request produce KB worth of log output

2022-03-14 08:46 UTC, pihme commented on testbench-prod.yaml
> +                  fieldPath: metadata.namespace
:question: Can you please explain how/why this works? I am curious to learn more about this.

2022-03-14 09:13 UTC, korthout commented on testbench-prod.yaml
> +                  fieldPath: metadata.namespace
Sure! What this does is set the value of the `ZCTB_LOG_STACKDRIVER_SERVICEVERSION` env var to the k8s namespace that this is deployed to. 

For example, we currently deploy to the namespaces `testbench-1-x-prod` and `testbench-1-x-dev`. That namespace is then used and we see that in the log explorer under `jsonPayload.serviceContext.version`. 

This same version value is used in the Error Reporting Tool for filtering. We already use this field in the same way in the benchmark project.

2022-03-14 09:15 UTC, korthout commented on core/src/main/resources/log4j2.xml
> +    <Logger name="io.zeebe.clustertestbench.cloud.filter" level="debug" additivity="false"/>
Yes, perhaps it's not necessary all the time. Note that it is currently configured like this as well

2022-03-14 09:15 UTC, pihme commented on testbench-prod.yaml
> +                  fieldPath: metadata.namespace
Ah, so it's not the version of StackDriver. It is the version that appears as metadata in log items. Got it! :bow:

2022-03-14 09:17 UTC, pihme commented on core/src/main/resources/log4j2.xml
> +    <Logger name="io.zeebe.clustertestbench.cloud.filter" level="debug" additivity="false"/>
Well, then this is a good moment to change it.

2022-03-15 08:36 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLogger.java
> +public final class JobHandlerWithEnrichedLogger implements JobHandler {
@deepthidevaki Might also be interesting for your e2e tests

2022-03-15 08:46 UTC, deepthidevaki commented on core/src/main/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLogger.java
> +public final class JobHandlerWithEnrichedLogger implements JobHandler {
Thanks. Looks like a good idea that we can adopt into e2e tests.

2022-03-15 10:13 UTC, korthout commented
@pihme I've applied your hints, and manually tested it. Please have another look

2022-03-15 10:20 UTC, pihme approved these changes
Thanks so much for putting in the time and effort (especially the logging and assembly and shading bit). 

:heart_eyes: I love this a lot! :heart_eyes:

2022-03-15 10:20 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLogger.java
> +    private static final List<String> JOB_VARIABLES =
:heart_eyes: Love it!

2022-03-15 10:20 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLogger.java
> +      JOB_VARIABLES.forEach(MDC::remove);
:heart_eyes: Love it!

2022-03-15 10:20 UTC, pihme commented on core/src/test/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLoggerTest.java
> +                assertThat(MDC.getCopyOfContextMap())
:wrench: I think this test would be more readable if it only tested the enriched logger in isolation

2022-03-15 10:24 UTC, korthout commented on core/src/test/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLoggerTest.java
> +                assertThat(MDC.getCopyOfContextMap())
Yeah, I thought about this. But wasn't sure how to improve things, so I just added a test that verified that the delegation works. If you have ideas on how to improve this quickly I'd be willing to look into it, but I don't want to spend too much time on this anymore 😄

2022-03-15 10:28 UTC, pihme commented on core/src/test/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLoggerTest.java
> +                assertThat(MDC.getCopyOfContextMap())
Pseudo code:
```
//when 
loggingEnricher = new LoggingEnricher(job)
map1 = MDC.getCopyOfContextMap())
loggingEnricher.close()
map2 = MDC.getCopyOfContextMap())

//then
assertThat(map1) ...
assertThat(map2).isEmpty()

```

2022-03-15 11:36 UTC, korthout commented on core/src/test/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLoggerTest.java
> +                assertThat(MDC.getCopyOfContextMap())
@pihme I've given it a quick try, let me know what you think.

2022-03-15 12:41 UTC, pihme commented on core/src/test/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLoggerTest.java
> +                assertThat(MDC.getCopyOfContextMap())
Looks good to me. To be safe, I would suggest to also call close in the first test.

2022-03-15 12:44 UTC, korthout commented
bors merge

2022-03-15 12:47 UTC, korthout commented
Seems like an unrelated build failure (some network connection issue). Let's retry that

bors merge

2022-03-15 12:49 UTC, merged