Introduce new call activity to run tests
zeebe-io/zeebe-cluster-testbench pull request #76
Opened 2020-10-29 11:08 UTC by Zelldon

As discussed I introduced a new call activity which can be used to delegate to the real test execution.
![run-sequential-test-in-camunda-cloud](https://user-images.githubusercontent.com/2758593/97560723-5e929c00-19df-11eb-9bb5-c818005b7ea4.png)

 An input mapping is used in the run all test workflow to execute the right test.

![run-all-tests-in-camunda-cloud](https://user-images.githubusercontent.com/2758593/97560738-62262300-19df-11eb-95cc-2edd11e9a7d6.png)

The tests are the sequential one and the chaos test  (which is currently empty)
![sequential-test](https://user-images.githubusercontent.com/2758593/97560758-681c0400-19df-11eb-9110-3bba463ff47b.png)
![chaos-test](https://user-images.githubusercontent.com/2758593/97560756-67836d80-19df-11eb-90c6-2215747fc088.png)

I don't know currently how to test it or whehter I should just push it to master which is why I created an PR :D

2020-10-29 12:41 UTC, pihme requested changes
Please rename the "run-sequential-test-in-camunda-cloud' 

Please also update the Readme (screenshots and documentation) to reflect the changes. In particular explain the new field _testId_

2020-10-29 12:41 UTC, pihme commented on workflows/run-all-tests-in-camunda-cloud.bpmn
> +          <zeebe:output source="=testResult" target="sequentialTestResult" />
please adjust output mapping here

2020-10-29 12:41 UTC, pihme commented on workflows/run-sequential-test-in-camunda-cloud.bpmn
> +    <bpmn:sequenceFlow id="Flow_15k26ho" sourceRef="prepare-zeebe-cluster-in-camunda-cloud" targetRef="Activity_17f0cpn" />
This file should be renamed now, as it is no longer specific to sequential tests

2020-10-29 12:42 UTC, pihme commented on workflows/run-sequential-test-in-camunda-cloud.bpmn
> +    <bpmn:sequenceFlow id="Flow_15k26ho" sourceRef="prepare-zeebe-cluster-in-camunda-cloud" targetRef="Activity_17f0cpn" />
e.g `run-test-in-camunda-cloud`

2020-10-29 12:48 UTC, Zelldon commented on workflows/run-sequential-test-in-camunda-cloud.bpmn
> +    <bpmn:sequenceFlow id="Flow_15k26ho" sourceRef="prepare-zeebe-cluster-in-camunda-cloud" targetRef="Activity_17f0cpn" />
I have seen that you normally have on the id the suffix `-process` are you fine to skip this? I think best practice is to have the same name as id.

2020-10-29 12:59 UTC, pihme commented on workflows/run-sequential-test-in-camunda-cloud.bpmn
> +    <bpmn:sequenceFlow id="Flow_15k26ho" sourceRef="prepare-zeebe-cluster-in-camunda-cloud" targetRef="Activity_17f0cpn" />
Sure, whatever is most common. I was making up conventions on the fly

2020-10-29 16:08 UTC, Zelldon commented
Hey @pihme I applied your review hints and made some other changes/improvements regarding `-process` suffix etc. Let me know if there is something missing.

2020-10-29 18:03 UTC, pihme requested changes
Great stuff, but not there yet.

- Some suggestions
- Didn't want to add your chaos test to `run-all-tests-camunda-cloud`
- two errors that need to be corrected

2020-10-29 18:03 UTC, pihme commented on workflows/run-test-in-camunda-cloud.bpmn
> +  <bpmn:process id="run-test-in-camunda-cloud" name="Run Sequential Test in Camunda Cloud" isExecutable="true">
In this process (but not related to this line):
* the _Notify Engineers_ task still has a header element "sequential test"; this should be removed

Also the class `NotifyEngineerWorkers` and `NotifyEngineerWorkers.Input` needs to be changed to read the testType from the variable `testId` and no longer from the `header`

2020-10-29 18:07 UTC, pihme commented on workflows/run-test-in-camunda-cloud.bpmn
> +  <bpmn:process id="run-test-in-camunda-cloud" name="Run Sequential Test in Camunda Cloud" isExecutable="true">
Optional, if you want to do it:
I have been thinking about removing the slack channel header field and moving it into an environment variable. 
Mostly for future proofing so that we can have different environments in the future. All the other settings which point to external resources are already externalized to environment variables.

But we can also do it later, no need to do it right now.

2020-10-29 18:38 UTC, Zelldon commented on README.md
> +| `testId` | The id of the test which should be run. Is used in the `Run Test` CallActivity | `String` |
Should I maybe rename it to testWorkflowId to be more specific?

2020-10-29 18:49 UTC, pihme commented on README.md
> +| `testId` | The id of the test which should be run. Is used in the `Run Test` CallActivity | `String` |
Sounds good!

2020-10-30 07:00 UTC, Zelldon commented on README.md
> +**Workflow ID:** `chaos-test`
If we rename it to `testWorfklowId` then I think we don't need that right?

2020-10-30 07:01 UTC, Zelldon commented on README.md
> +| `testId` | The id of the test which should be run. | `String` |
Since it is copied as variable to the workflow instance I thought I need to add it here :) but I can also remove it

2020-10-30 07:05 UTC, Zelldon commented on workflows/run-all-tests-in-camunda-cloud.bpmn
>            <zeebe:input source="=sequentialTestParams" target="testParams" />
Weird it seems all changes for this workflows are missing :roll_eyes:

2020-10-30 07:29 UTC, pihme commented on README.md
> +| `testId` | The id of the test which should be run. | `String` |
My thinking here is that I would like to list only the variables which are needed for this process, not variables which it inherits from somewhere else. After all, the process should be reusable and shall be called in different contexts. 
Also this will reduce documentation maintenance and duplication.
So if e.g. _Record Test Results_ needs it, we should leave it in. If no service task needs it, we should remove it.

2020-10-30 07:35 UTC, pihme requested changes

2020-10-30 07:35 UTC, pihme commented on README.md
> +
What is missing here is: 

Needed for Run Sequential Tests

- authenticationDetails

Needed for report test results

- clusterId;
- clusterName;
- operateURL;

2020-10-30 09:28 UTC, Zelldon commented on README.md
> +
Are the uuids necessary here? Should I remove them from the doc?

2020-10-30 09:42 UTC, Zelldon commented
Hey @pihme I think I have applied all reviews hints. Let me know if there is something missing.

2020-10-30 13:43 UTC, pihme requested changes
Sorry, but this will break our daily tests.

`Run all Tests in Camunda Cloud` expects a `testResult` in the chaos test branch, but there is no-one which adds such a variable.

2020-10-30 13:43 UTC, pihme commented on README.md
> +**Workflow ID:** `prepare-zeebe-cluster-in-camunda-cloud`
This file, chapter _Service Tasks_ row _Notify Engineers_ remove header `testType`

2020-10-30 13:43 UTC, pihme commented on workflows/run-all-tests-in-camunda-cloud.bpmn
> +          <zeebe:output source="=testResult" target="sequentialTestResult" />
```suggestion

```

In the future it should probably be:
`<zeebe:output source="=testResult" target="sequentialTestResult" />` -> `<zeebe:output source="=testResult" target="chaosTestResult" />`

But today, if you would run it, then Zeebe will complain that it cannot find `testResult`, because there isn't any yet. So again, maybe better leave it out for now and add it later.

2020-10-30 13:43 UTC, pihme commented on workflows/run-all-tests-in-camunda-cloud.bpmn
> +          <zeebe:input source="=sequentialTestParams" target="testParams" />
```suggestion

```
It should probably be `chaosTestParams`. If you want to leave it in as a placeholder, you also need to add it `daily-test-protocol->Run All Tests in ...->Input/Output Mapping`

So maybe better to leave it out for new and add it later

2020-10-30 13:43 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/notification/NotificationService.java
> +   * @param target the target where the message should be send to
```suggestion
   * @param target the target where the message should be sent to
```

2020-10-30 13:43 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/notification/NotificationService.java
> +   * @param message the message which should be send
```suggestion
   * @param message the message which should be sent
```

2020-10-30 13:43 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/NotifyEngineersWorker.java
> +		resultBuilder.append("_").append(input.testWorkflowId).append("_") //
```suggestion
		resultBuilder.append("_").append(input.getTestWorkflowId()).append("_") //
```

2020-10-30 13:43 UTC, pihme commented on core/src/test/java/io/zeebe/clustertestbench/worker/NotifyEngineersWorkerTest.java
> +    verify(jobClientMock).newCompleteCommand(0xCAFEL);
What is `0xCAFEL`???

2020-10-30 13:43 UTC, pihme commented on core/src/test/java/io/zeebe/clustertestbench/worker/NotifyEngineersWorkerTest.java
> +    verify(jobClientMock, times(0)).newCompleteCommand(0xCAFEL);
There is also `Mockito.never()`

Maybe also better to check for `verify(jobClientMock, times(0)).newCompleteCommand(Mockito.any());`

But this is more an aesthetic comment. Feel free to adopt or ignore.

2020-11-02 08:05 UTC, Zelldon commented on core/src/test/java/io/zeebe/clustertestbench/worker/NotifyEngineersWorkerTest.java
> +    verify(jobClientMock).newCompleteCommand(0xCAFEL);
I like to use this more speaking value then 1 or zero :shrug: it is hex int `0xCAFE` + L for long.

2020-11-02 10:43 UTC, pihme approved these changes
Looks good to me!

2020-11-02 10:47 UTC, Zelldon commented
:tada: Thanks !

2020-11-02 10:47 UTC, Zelldon commented
Do I need to bors here? :D Or just merge?

2020-11-02 10:48 UTC, pihme commented
bors is enabled; you can also just merge, whatever you prefer

2020-11-02 12:14 UTC, Zelldon commented
bors r+

2020-11-02 12:17 UTC, merged