53 create generation on demand
zeebe-io/zeebe-cluster-testbench pull request #79
Opened 2020-10-30 10:49 UTC by pihme

closes #53

2020-10-30 15:13 UTC, pihme commented
@Zelldon still uses the old process names. I need to adapt that after your PR is merged.

2020-11-02 14:09 UTC, pihme commented
Rebased to have the latest changes; changed process call to reflect new naming convention

2020-11-04 09:07 UTC, Zelldon requested changes
Hey @pihme I'm 80%  complete with your review, but I will post it already since I currently working on another critical issue and I want to unblock you. I will review the rest later. I think in general it looks good just a smaller things and I would like that we remove or replace the cache.

2020-11-04 09:15 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/KeyedOAuthCredentialsCache.java
> +	private static final Map<Object, OAuthCredentials> cachedCredentials = new HashMap<>();
Let's talk about it. It is unclear to me what your desired outcome is (no cache, non static cache; which Agrona collection)

2020-11-04 09:15 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthServiceAccountTokenRequest.java
> +	}
Nope, IDE generated

2020-11-04 09:17 UTC, pihme commented on testbench.yaml
> +	            key: internalCloudPassword
- I want to be able to take the image and deploy it to different environments (e.g int vs. dev)
- Ideally, I want to be able to change secrets without having to reuild the Docker image.

2020-11-04 09:18 UTC, pihme commented on core/src/test/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorkerTest.java
> +		CreateGenerationInCamundaCloudWorker sut;
Which bit? The `sut` ,or the long class name, or worker vs. handler?

2020-11-04 09:19 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +public class CreateGenerationInCamundaCloudWorker implements JobHandler {
What is the difference?

2020-11-04 09:20 UTC, pihme commented on README.md
> +| `channel` | name of the channel for the tests | `String` |
Defines in which channel the test clusters will be generated

2020-11-04 09:22 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
Maybe, idk

2020-11-04 09:22 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +public class CreateGenerationInCamundaCloudWorker implements JobHandler {
The handler is just handling the job. The worker is provided by the clients and contains the logic of asking/polling for new job and forwarding the jobs to the handlers. The worker normally consists of multiple threads for polling and calling handlers and it can also fail or complete the job automatically after the job handler was called.

2020-11-04 09:22 UTC, Zelldon commented on core/src/test/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorkerTest.java
> +		CreateGenerationInCamundaCloudWorker sut;
This `sut`

2020-11-04 09:22 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		internalApiClient.createGeneration(createGenerationrequest);
There is no response from the backend API

2020-11-04 09:23 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		internalApiClient.updateChannel(channelInfo.getUuid(), updateChannelRequest);
We must add the generation to the allowed generations of that channel. Otherwise, the generation exists, but you cannot create clusters with that generation

2020-11-04 09:24 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/DeleteGenerationInCamundaCloudWorker.java
> +		internalApiClient.deleteGeneration(input.getGenerationUUID());
No, when the generation is deleted, the backend removes it from the channels automatically.

2020-11-04 09:26 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/DeleteGenerationInCamundaCloudWorker.java
> +		client.newCompleteCommand(job.getKey()).send().join();
If we add it, yes; if we replace it, no. (it is easier to pass a key around to external proesses than to pass around the job object)

2020-11-04 09:27 UTC, pihme commented on core/src/test/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorkerTest.java
> +	class HandleJobTest {
No need. Just for grouping of tests. Also having nested test classes allows you to have setup/teardown methods just for that test class

2020-11-04 09:49 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		} catch (Throwable t) {
If you don't, how do you then clean up again?

2020-11-04 10:20 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthUserAccountTokenRequest.java
> +	}
Ouch, that was generated by IntelliJ? What about NPEs?

Well, if we are talking about aesthetic preferences, I like this one best:
```
	@Override
	public int hashCode() {
		return Objects.hash(audience, clientId, clientSecret, grantType, password, username);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OAuthUserAccountTokenRequest other = (OAuthUserAccountTokenRequest) obj;
		return Objects.equals(audience, other.audience) && Objects.equals(clientId, other.clientId)
				&& Objects.equals(clientSecret, other.clientSecret) && Objects.equals(grantType, other.grantType)
				&& Objects.equals(password, other.password) && Objects.equals(username, other.username);
	}
```

2020-11-04 15:18 UTC, Zelldon commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthUserAccountTokenRequest.java
> +	}
I think I can choose between different templates. I was just wondering why the previous equals look to weird :sweat_smile:

2020-11-04 15:18 UTC, Zelldon commented on testbench.yaml
> +	            key: internalCloudPassword
makes sense

2020-11-04 15:19 UTC, Zelldon commented on README.md
> +| `channel` | name of the channel for the tests | `String` |
Maybe we add this information?

2020-11-04 15:20 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
:laughing: lets use the same styleguide as in the main project, so spaces

2020-11-04 15:23 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		} catch (Throwable t) {
If you catch throwable this also means you catch OutOfMemory, your application will not behave in the same way as normal and this can cause unexpected behavior, right? It is not guaranteed that you're able to clean up here.

2020-11-04 15:23 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		internalApiClient.createGeneration(createGenerationrequest);
ok weird

2020-11-04 15:24 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		internalApiClient.updateChannel(channelInfo.getUuid(), updateChannelRequest);
interesting ^^

2020-11-04 15:24 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/DeleteGenerationInCamundaCloudWorker.java
> +		client.newCompleteCommand(job.getKey()).send().join();
What do you mean with replace?

2020-11-04 15:27 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/DeleteGenerationInCamundaCloudWorker.java
> +		client.newCompleteCommand(job.getKey()).send().join();
If we have the method `newCompleteCommand(job)` instead of `newCompleteCommand(jobKey)` and the other method is the only method in the client

2020-11-04 15:28 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
If you tell me how to integrate that into Eclipse or Maven, sure.

2020-11-04 15:33 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		} catch (Throwable t) {
That sounds like a contrived scenario. Please let's discuss that.

2020-11-04 15:33 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
* https://github.com/zeebe-io/zeebe/wiki/Code-Style 
* https://github.com/zeebe-io/zeebe/blob/develop/parent/pom.xml#L1046-L1059
* https://github.com/zeebe-io/zeebe/blob/develop/parent/pom.xml#L843-L877

2020-11-04 15:33 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthUserAccountTokenRequest.java
> +	}
Eclipse default

2020-11-04 15:33 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
Can be a separate issue of course

2020-11-04 15:34 UTC, Zelldon commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthUserAccountTokenRequest.java
> +	}
I thought you are using intellij :sweat_smile: :laughing:

2020-11-04 15:40 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthUserAccountTokenRequest.java
> +	}
On Zeebe yes, because it doesn't play nice with Eclipse. For other projects I jump back and force between the two. 
I find IntelliJ is better for working inside a seasoned code base. When you know the code base very well and most of what you do is refactoring.

I prefer Eclipse for writing new code, and working with dependencies that are new to me.

2020-11-04 15:41 UTC, Zelldon commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthUserAccountTokenRequest.java
> +	}
Ah interesting :+1:

2020-11-04 15:44 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
Sigh, I was hoping I can delay that a little longer...
But alas #90, #91 
Don't fully understand checkstyle and the dependency to zeebe build tools, tbh.

2020-11-04 15:45 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
Hehe but not if you want to work with me :laughing: I can do that if you want.

2020-11-04 15:57 UTC, pihme commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		this.internalApiClient = internalApiClient;
Let's share the burdon. I do #90, you can take #91

2020-11-05 07:41 UTC, Zelldon requested changes

2020-11-05 07:41 UTC, Zelldon commented on internal-cloud-client/src/main/java/io/zeebe/clustertestbench/internal/cloud/request/UpdateChannelRequest.java
> +			List<String> allowedGeneerationIds) {
```suggestion
			List<String> allowedGenerationIds) {
```

2020-11-05 07:41 UTC, Zelldon commented on internal-cloud-client/src/main/java/io/zeebe/clustertestbench/internal/cloud/request/UpdateChannelRequest.java
> +		this.allowedGenerationIds = allowedGeneerationIds;
```suggestion
		this.allowedGenerationIds = allowedGenerationIds;
```

2020-11-05 07:41 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/bootstrap/Launcher.java
> +		return client;
```suggestion
		return new InternalCloudAPIClientFactory().createCloudAPIClient(internalCloudApiUrl,
				serverUrl, audience, clientId, clientSecret, username, password);
```

2020-11-05 07:42 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/CreateGenerationInCamundaCloudWorker.java
> +		} catch (Throwable t) {
Not really.

2020-11-05 07:45 UTC, Zelldon commented on core/src/main/java/io/zeebe/clustertestbench/worker/DeleteGenerationInCamundaCloudWorker.java
> +		client.newCompleteCommand(job.getKey()).send().join();
No we cant replace it otherwise we are not backwards compatible. I would just suggest to add it.

2020-11-05 08:15 UTC, Zelldon commented
@pihme I created a new branch with an example implementation with concurrent hash map https://github.com/zeebe-io/zeebe-cluster-testbench/tree/zell-example-cache With that you follow DI principile and have not a static class/field etc which makes it hard to test etc.

2020-11-05 08:22 UTC, pihme commented
@Zelldon I would rather get rid of the cache entirely and use the same client instance for all handlers. That's what I wanted to discuss with you.

2020-11-05 08:28 UTC, pihme commented on workflows/qa-protocol.bpmn
> +          <zeebe:input source="=[&#34;Development&#34;, &#34;Production - S&#34;, &#34;Production - M&#34;, &#34;Production - L&#34;]" target="clusterPlans" />
No. Those are the names of the cluster plans in the cloud. As they are displayed in the UI and used in the backend.
We also have UUIDs for each of them, if that suits you better.

2020-11-05 08:30 UTC, Zelldon commented on workflows/qa-protocol.bpmn
> +          <zeebe:input source="=[&#34;Development&#34;, &#34;Production - S&#34;, &#34;Production - M&#34;, &#34;Production - L&#34;]" target="clusterPlans" />
Ah ok thanks then I need to replace the whitespace in my workers. Its fine thanks

2020-11-05 19:48 UTC, Zelldon reviewed
Looks good :+1:  just a note to the volatile field

2020-11-05 19:48 UTC, Zelldon commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthInterceptor.java
>  			credentials = credentialSupplier.get();
I think this is not really threadsafe

2020-11-05 19:48 UTC, Zelldon commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthInterceptor.java
>  			credentials = credentialSupplier.get();
Either we need a lock here or a compare and swap with atomic reference

2020-11-06 06:21 UTC, pihme commented on cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthInterceptor.java
>  			credentials = credentialSupplier.get();
It doesn't need to be threadsafe. The only purpose of this cached value is so that we don't request a new token before each request. That's why it is cached. However, if we overwrite a valid token no harm is  done.

I added a lock to make you happy.

Can we please merge this thing now?

2020-11-06 06:36 UTC, Zelldon approved these changes

2020-11-06 06:39 UTC, pihme commented
doing rebase now

2020-11-06 06:53 UTC, pihme commented
reducing commits now

2020-11-06 07:07 UTC, pihme commented
bors r+

2020-11-06 07:10 UTC, merged